---
- name: Test LDAP EE
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check ldapsearch
      command: ldapsearch -VV
      register: ldap_version

    - debug:
        var: ldap_version.stdout_lines