#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/user_offboarding
uac_disable_bit: 2
target_samaccountname: "usera"
ldap_search_base: "DC=lab,DC=local"

azure_sync_group_dn: "CN=AzureSyncUsers,CN=Users,DC=lab,DC=local"