#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/offboarding_ad
uac_disable_bit: 2
target_samaccountname: "mail.test3"
ldap_search_base: "DC=welab,DC=co,DC=id"

azure_sync_group_dn: "CN=AADCSync,OU=Azure,OU=Cloud,OU=Application,OU=Welabid,DC=welab,DC=co,DC=id"
